(() => {
'use strict';
const VERSION='3.6.2';
const enc=new TextEncoder(), dec=new TextDecoder();
let gestionSelectedId=null;
const q=id=>document.getElementById(id);
function xmlEscape(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[c]))}
function stripSequencePrefix(v){return String(v??'').replace(/^\s*\d+\s*[-.)]\s*/, '').trim()}
function presentationParts(value,fallback={}){let s=String(value||'').trim(),m=s.match(/^(\d{4})\s*-\s*(\d+)(?:\s*-\s*C)?$/i);return m?{tomo:m[1],asiento:m[2]}:{tomo:String(fallback.tomo||''),asiento:String(fallback.asiento||'')}}
function moduleCase(module){let id={tramites:currentPre,pre:currentPre,inspection:currentInspection,calificacion:currentMotor,cierre:currentClose,gestion:gestionSelectedId}[module];return expedientes.find(x=>x.id===Number(id))||expedientes.find(x=>!x.finalizado)||expedientes[0]||null}
function appendModuleObservation(e,module){if(!e)return;let label={tramites:'Trámites',pre:'Precalificación',inspection:'Inspección',calificacion:'Calificación',cierre:'Resoluciones',gestion:'Gestión'}[module]||module,stamp=new Date().toLocaleString('es-CR'),text=`${label}: datos guardados y avance registrado.`;e.observaciones=String(e.observaciones||'').trim();e.observaciones=e.observaciones?`${e.observaciones}\n${text}`:text;e.observacionesHistorial=Array.isArray(e.observacionesHistorial)?e.observacionesHistorial:[];e.observacionesHistorial.push({modulo:label,observacion:text,fecha:new Date().toISOString()});return text}
function silentSave(module,e){if(!e)return;
 if(module==='pre'){Object.entries(COND_FIELDS).forEach(([key,id])=>e.cond[key]=!!q(id)?.checked);updateDecision(e)}
 if(module==='inspection'){e.inspection.observaciones=q('inspectionObs')?.value||e.inspection.observaciones||'';e.inspection.guardada=true;let first=e.inspection.accesos[0]||emptyAccess();e.inspection.anchoCallePlanoMadre=first.anchoPlano;e.inspection.anchoCalleInspeccion=first.anchoInspeccion;e.inspection.referenciaMedicion=first.referencia;e.inspection.distanciaDesdeLC=first.desdeLC;e.inspection.distanciaDesdeLCInspeccion=first.desdeLCInspeccion;e.inspection.acceso=first.tipo;e.inspection.diferenciaAncho=accessEval(first).difference;updateDecision(e);e.estado=e.dictamen==='PENDIENTE'?'EN INSPECCIÓN':'LISTO PARA CALIFICACIÓN'}
 if(module==='calificacion'){e.calificacionEncargado=q('calificador')?.value.trim()||e.calificacionEncargado||'';e.fechaCalificacion=new Date().toISOString();e.report=e.report||{};if(!e.report.fecha)e.report.fecha=typeof localDateISO==='function'?localDateISO():new Date().toISOString().slice(0,10);updateDecision(e)}
 if(module==='cierre'){saveReportFieldsSilent(e)}
 appendModuleObservation(e,module);persist();renderAll()}
function nextModule(module){let e=moduleCase(module);silentSave(module,e);let next={tramites:'pre',pre:'inspection',inspection:'calificacion',calificacion:'cierre',cierre:'gestion',gestion:'tramites'}[module]||'tramites';go(next)}
window.nextModule=nextModule;

function renderGestion(){let body=q('gestionBody');if(!body)return;let s=foldName(q('gSearch')?.value||''),estado=q('gEstado')?.value||'',res=q('gResultado')?.value||'',dist=q('gDistrito')?.value||'';
 let estados=[...new Set(expedientes.map(e=>e.estado).filter(Boolean))].sort(),districts=[...new Set(expedientes.map(e=>e.distrito||'Sin distrito'))].sort();let es=q('gEstado'),ds=q('gDistrito');if(es){let old=es.value;es.innerHTML='<option value="">Todos</option>'+estados.map(v=>`<option>${esc(v)}</option>`).join('');es.value=old}if(ds){let old=ds.value;ds.innerHTML='<option value="">Todos</option>'+districts.map(v=>`<option>${esc(v)}</option>`).join('');ds.value=old}
 let rows=expedientes.filter(e=>(!s||foldName([e.tramite,e.folio,e.presentacion,e.solicitante,e.lugar,e.distrito].join(' ')).includes(s))&&(!estado||e.estado===estado)&&(!res||e.dictamen===res)&&(!dist||(e.distrito||'Sin distrito')===dist));q('gestionSummary').textContent=`${rows.length} de ${expedientes.length} trámites`;body.innerHTML=rows.length?rows.map(e=>{let a=ageInfo(e),sel=e.id===gestionSelectedId?' selected':'';return `<tr class="click${sel}" onclick="selectGestion(${e.id})"><td><b>${esc(e.tramite||caseRef(e))}</b></td><td>${esc(e.fecha||'')}<div><span class="pill ${a.className||'blue'}">${esc(a.label)}</span></div></td><td>${esc(e.folio||'')}</td><td>${esc(e.presentacion||'')}</td><td>${esc(e.solicitante||'')}</td><td>${esc(e.distrito||'Sin distrito')}<div class="small">${esc(e.lugar||'')}</div></td><td>${statusPill(e)}</td><td><span class="pill ${e.dictamen==='RECHAZADO'?'red':e.dictamen==='APROBADO'?'green':'amber'}">${esc(e.dictamen||'PENDIENTE')}</span></td><td>${esc(e.observaciones||'')}</td></tr>`}).join(''):'<tr><td colspan="9" class="empty">Sin resultados</td></tr>';}
function selectGestion(id){gestionSelectedId=Number(id);let e=expedientes.find(x=>x.id===gestionSelectedId);q('gestionSelected').textContent=e?`Seleccionado: ${caseRef(e)}`:'Seleccione una fila para registrar la observación de Gestión.';renderGestion()}
function clearGestionFilters(){['gSearch','gEstado','gResultado','gDistrito'].forEach(id=>{if(q(id))q(id).value=''});renderGestion()}
window.renderGestion=renderGestion;window.selectGestion=selectGestion;window.clearGestionFilters=clearGestionFilters;
['gSearch','gEstado','gResultado','gDistrito'].forEach(id=>{let el=q(id);if(el)el.addEventListener(id==='gSearch'?'input':'change',renderGestion)});

// ZIP helpers (STORE writer + existing app reader for deflate/store).
const CRC_TABLE=(()=>{let t=new Uint32Array(256);for(let n=0;n<256;n++){let c=n;for(let k=0;k<8;k++)c=(c&1)?0xedb88320^(c>>>1):c>>>1;t[n]=c>>>0}return t})();
function crc32(bytes){let c=0xffffffff;for(const b of bytes)c=CRC_TABLE[(c^b)&255]^(c>>>8);return (c^0xffffffff)>>>0}
function u16(v){return [v&255,(v>>>8)&255]} function u32(v){return [v&255,(v>>>8)&255,(v>>>16)&255,(v>>>24)&255]}
function concat(parts){let len=parts.reduce((n,p)=>n+p.length,0),out=new Uint8Array(len),o=0;for(const p of parts){out.set(p,o);o+=p.length}return out}
function zipStore(entries){let local=[],central=[],offset=0;for(const ent of entries){let name=enc.encode(ent.name),data=ent.bytes instanceof Uint8Array?ent.bytes:new Uint8Array(ent.bytes),crc=crc32(data),lh=new Uint8Array([...u32(0x04034b50),...u16(20),...u16(0x800),...u16(0),...u16(0),...u16(0),...u32(crc),...u32(data.length),...u32(data.length),...u16(name.length),...u16(0),...name]);local.push(lh,data);let ch=new Uint8Array([...u32(0x02014b50),...u16(20),...u16(20),...u16(0x800),...u16(0),...u16(0),...u16(0),...u32(crc),...u32(data.length),...u32(data.length),...u16(name.length),...u16(0),...u16(0),...u16(0),...u16(0),...u32(0),...u32(offset),...name]);central.push(ch);offset+=lh.length+data.length}let c=concat(central),l=concat(local),end=new Uint8Array([...u32(0x06054b50),...u16(0),...u16(0),...u16(entries.length),...u16(entries.length),...u32(c.length),...u32(l.length),...u16(0)]);return concat([l,c,end])}
function identifiersFromName(name){let t=(name.match(/(?:VMSDC|MS-VDCT)[ _-]*\d{2,4}[ _-]*\d{1,10}/i)||[])[0]||'',f=(name.match(/\b\d{1,2}[ _-]\d{5,10}[ _-]\d{3}\b/)||[])[0]||'',p=(name.match(/\b\d{4}[ _-]\d{3,10}(?:[ _-]C)?\b/i)||[])[0]||'';return {tramite:t.replace(/_/g,' ').trim(),folio:f.replace(/_/g,'-').trim(),presentacion:p.replace(/_/g,'-').trim()}}
function attachMeta(e,name,type,size,zipName,ids){if(!e)return;e.archivosAdjuntos=Array.isArray(e.archivosAdjuntos)?e.archivosAdjuntos:[];let key=`${zipName}|${name}`;if(!e.archivosAdjuntos.some(x=>x.clave===key))e.archivosAdjuntos.push({clave:key,nombre:name,tipo:type,tamano:size,origenZip:zipName,identificadores:ids,fecha:new Date().toISOString()})}
async function importZip(files){let stats=statsNew();stats.files=files.length;let attachments=0;for(const zf of files){try{let zb=new Uint8Array(await zf.arrayBuffer()),dir=zipDirectory(zb);for(const [name,entry] of Object.entries(dir)){if(name.endsWith('/'))continue;let bytes=await unzipEntry(zb,entry),lower=name.toLowerCase(),file=new File([bytes],name,{type:'application/octet-stream'}),results=[];
  try{if(lower.endsWith('.json')){let v=JSON.parse(dec.decode(bytes));for(const r of jsonImportRows(v))results.push(upsertImported(r,{name:`${zf.name}/${name}`,type:'ZIP-JSON'}))}
  else if(lower.endsWith('.csv')){let parsed=parseCsv(dec.decode(bytes));for(const r of parsed.rows||[])results.push(upsertImported(r,{name:`${zf.name}/${name}`,type:'ZIP-CSV'}))}
  else if(lower.endsWith('.xlsx')){let parsed=await parseXlsx(file);for(const r of parsed.rows||[])results.push(upsertImported(r,{name:`${zf.name}/${name}`,type:'ZIP-Excel'}))}
  else if(lower.endsWith('.pdf')){let text=await pdfStrings(bytes),r=pdfRecord(text);if(hasIdentifier(mapHeaders(r)))results.push(upsertImported(r,{name:`${zf.name}/${name}`,type:'ZIP-PDF'}))}
  }catch(err){console.warn('Archivo interno no interpretado',name,err)}
  results.forEach(r=>statsAdd(stats,r));let ids=identifiersFromName(name),target=null;for(const r of results){if(r?.id){target=expedientes.find(e=>e.id===r.id);if(target)break}}if(!target&&hasIdentifier(mapHeaders(ids))){let ms=findIdentifierMatches(mapHeaders(ids));target=ms[0]||null}if(target){attachMeta(target,name,lower.split('.').pop().toUpperCase(),bytes.length,zf.name,ids);attachments++}
 }
 }catch(err){stats.skipped++;stats.warnings.push(`${zf.name}: ${err.message}`)}}persist();renderAll();q('importMsg').textContent=`ZIP: ${stats.new} nuevo(s) · ${stats.updated} actualizado(s) · ${stats.assigned} X→trámite asignado(s) · ${attachments} archivo(s) enlazado(s)`}
window.importZip=importZip;let zinput=q('fileZip');if(zinput)zinput.onchange=e=>importZip([...e.target.files]);

// XLSX export with one sheet and a JSON-full-data column.
function colName(n){let s='';for(n++;n;n=Math.floor((n-1)/26))s=String.fromCharCode(65+(n-1)%26)+s;return s}
function xlsxCell(v,r,c){let ref=colName(c)+(r+1);if(typeof v==='number')return `<c r="${ref}"><v>${v}</v></c>`;return `<c r="${ref}" t="inlineStr"><is><t xml:space="preserve">${xmlEscape(v??'')}</t></is></c>`}
function gestionXlsxBytes(){let headers=['Trámite','Fecha solicitud','Folio real','Plano','Presentación','Tomo','Asiento','Área','Solicitante','Correo','Distrito','Lugar','Tipo ingreso','Modalidad','Responsable','Estado','Resultado','Finalizado','Observaciones','Archivos adjuntos','Información completa JSON'],rows=expedientes.map(e=>{let pp=presentationParts(e.presentacion,e);return [e.tramite,e.fecha,e.folio,e.plano,e.presentacion,pp.tomo,pp.asiento,e.area,e.solicitante,e.correo,e.distrito,e.lugar,e.ingreso,e.modalidad,e.responsable,e.estado,e.dictamen,e.finalizado?'Sí':'No',e.observaciones,(e.archivosAdjuntos||[]).map(x=>x.nombre).join(' | '),JSON.stringify(e)]});let all=[headers,...rows],sheetRows=all.map((row,r)=>`<row r="${r+1}">${row.map((v,c)=>xlsxCell(v,r,c)).join('')}</row>`).join(''),sheet=`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetViews><sheetView workbookViewId="0"><pane ySplit="1" topLeftCell="A2" activePane="bottomLeft" state="frozen"/></sheetView></sheetViews><sheetData>${sheetRows}</sheetData><autoFilter ref="A1:U${all.length}"/></worksheet>`,wb=`<?xml version="1.0" encoding="UTF-8"?><workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets><sheet name="Trámites" sheetId="1" r:id="rId1"/></sheets></workbook>`,rels=`<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/></Relationships>`,rootrels=`<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>`,ct=`<?xml version="1.0" encoding="UTF-8"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/></Types>`;return zipStore([{name:'[Content_Types].xml',bytes:enc.encode(ct)},{name:'_rels/.rels',bytes:enc.encode(rootrels)},{name:'xl/workbook.xml',bytes:enc.encode(wb)},{name:'xl/_rels/workbook.xml.rels',bytes:enc.encode(rels)},{name:'xl/worksheets/sheet1.xml',bytes:enc.encode(sheet)}])}
function blobDownload(bytes,name,type){let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([bytes],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1500)}
function exportGestionExcel(){blobDownload(gestionXlsxBytes(),`C_VISADOS_GESTION_${new Date().toISOString().slice(0,10)}.xlsx`,'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet')}
window.exportGestionExcel=exportGestionExcel;

// Definitive office template patching.
// The definitive DOCX files are read-only sources. Only variable XML text/rows are patched in the generated copy.
const WNS='http://schemas.openxmlformats.org/wordprocessingml/2006/main';
async function zipEntries(bytes){let dir=zipDirectory(bytes),out=[];for(const name of Object.keys(dir))out.push({name,bytes:await unzipEntry(bytes,dir[name])});return out}
function wEl(doc,local){return doc.createElementNS(WNS,'w:'+local)}
function childNS(el,local){return [...el.childNodes].find(n=>n.nodeType===1&&n.namespaceURI===WNS&&n.localName===local)||null}
function setParagraphText(p,newText){let ts=[...p.getElementsByTagNameNS(WNS,'t')];if(!ts.length){let r=wEl(p.ownerDocument,'r'),t=wEl(p.ownerDocument,'t');r.appendChild(t);p.appendChild(r);ts=[t]}ts[0].textContent=String(newText??'');for(let i=1;i<ts.length;i++)ts[i].textContent='';let space='http://www.w3.org/XML/1998/namespace';if(/^\s|\s$/.test(String(newText??'')))ts[0].setAttributeNS(space,'xml:space','preserve');return true}
function ensurePPr(p){let pr=childNS(p,'pPr');if(!pr){pr=wEl(p.ownerDocument,'pPr');p.insertBefore(pr,p.firstChild)}return pr}
function ensureTrPr(tr){let pr=childNS(tr,'trPr');if(!pr){pr=wEl(tr.ownerDocument,'trPr');tr.insertBefore(pr,tr.firstChild)}return pr}
function addUniqueProp(parent,local){let found=childNS(parent,local);if(!found){found=wEl(parent.ownerDocument,local);parent.appendChild(found)}return found}
function keepParagraphTogether(p,withNext=false){let pr=ensurePPr(p);addUniqueProp(pr,'keepLines');if(withNext)addUniqueProp(pr,'keepNext')}
function makeRowAtomic(tr){let pr=ensureTrPr(tr);[...pr.getElementsByTagNameNS(WNS,'trHeight')].forEach(n=>n.remove());addUniqueProp(pr,'cantSplit')}
function repeatHeaderRow(tr){let pr=ensureTrPr(tr);addUniqueProp(pr,'tblHeader');makeRowAtomic(tr)}
function replaceExactParagraphs(xml,repls,removeColon=false){let doc=new DOMParser().parseFromString(xml,'application/xml'),ps=[...doc.getElementsByTagNameNS(WNS,'p')];for(const p of ps){let ts=[...p.getElementsByTagNameNS(WNS,'t')],text=ts.map(t=>t.textContent).join('');let norm=text.replace(/\s+/g,' ').trim();if(removeColon&&norm===':'){setParagraphText(p,'');continue}for(const [oldv,newv] of repls){if(norm===String(oldv).replace(/\s+/g,' ').trim()){setParagraphText(p,String(newv??''));break}}}return new XMLSerializer().serializeToString(doc)}
function replaceTextAcrossNodes(xml,oldv,newv){let doc=new DOMParser().parseFromString(xml,'application/xml'),ps=[...doc.getElementsByTagNameNS(WNS,'p')];for(const p of ps){let ts=[...p.getElementsByTagNameNS(WNS,'t')],vals=ts.map(t=>t.textContent||''),joined=vals.join(''),start=joined.indexOf(oldv);if(start<0)continue;let end=start+oldv.length,pos=0,first=true;for(let i=0;i<ts.length;i++){let v=vals[i],a=pos,b=pos+v.length;pos=b;if(b<=start||a>=end)continue;let left=start>a?v.slice(0,start-a):'',right=end<b?v.slice(end-a):'';ts[i].textContent=left+(first?String(newv??''):'')+right;first=false}break}return new XMLSerializer().serializeToString(doc)}
function replaceObservationParagraph(doc,p,items){let parent=p.parentNode,template=p.cloneNode(true),vals=items.length?items:['Sin observaciones adicionales.'];for(let i=0;i<vals.length;i++){let cp=template.cloneNode(true);setParagraphText(cp,`${i+1}. ${vals[i]}`);keepParagraphTogether(cp,false);parent.insertBefore(cp,p)}parent.removeChild(p)}
function setReasonRow(row,index,item){makeRowAtomic(row);let cells=[...row.getElementsByTagNameNS(WNS,'tc')];if(cells.length<2)return;let lp=[...cells[0].getElementsByTagNameNS(WNS,'p')][0],rp=[...cells[1].getElementsByTagNameNS(WNS,'p')][0];setParagraphText(lp,`${index}- ${stripSequencePrefix(item.motivation||item.detalle||'')}`);setParagraphText(rp,`${index}- ${stripSequencePrefix(item.fund||'')}`);keepParagraphTogether(lp,false);keepParagraphTogether(rp,false)}
function patchReasonTable(doc,items){let tables=[...doc.getElementsByTagNameNS(WNS,'tbl')],tbl=tables[3];if(!tbl)return;let rows=[...tbl.childNodes].filter(n=>n.nodeType===1&&n.namespaceURI===WNS&&n.localName==='tr');if(rows[0])repeatHeaderRow(rows[0]);let template=rows[1]?rows[1].cloneNode(true):null;if(!template)return;for(let i=1;i<rows.length;i++)tbl.removeChild(rows[i]);let vals=items.length?items:[{motivation:'Sin motivación técnica registrada.',fund:''}];vals.forEach((it,i)=>{let row=template.cloneNode(true);setReasonRow(row,i+1,it);tbl.appendChild(row)})}
function protectClosingBlocks(doc){let tables=[...doc.getElementsByTagNameNS(WNS,'tbl')];[2,4,5].forEach(i=>{if(tables[i])[...tables[i].getElementsByTagNameNS(WNS,'tr')].forEach(makeRowAtomic)});let ps=[...doc.getElementsByTagNameNS(WNS,'p')];for(const p of ps){let norm=[...p.getElementsByTagNameNS(WNS,'t')].map(t=>t.textContent).join('').replace(/\s+/g,' ').trim();if(norm==='Sin más por el momento, me despido.'||norm==='Atentamente;')keepParagraphTogether(p,true);if(norm.startsWith('NOTA: EL TRÁMITE QUEDA SUJETO'))keepParagraphTogether(p,false)}}
function patchRejectionBody(xml,e){let doc=new DOMParser().parseFromString(xml,'application/xml'),ps=[...doc.getElementsByTagNameNS(WNS,'p')],defs=allRejectReasons(e),obs=rejectionObservationItems(e),exact=new Map([['09 de julio del 2026',dateEs(e.report?.fecha||e.fechaCalificacion?.slice(0,10)||e.fecha)],['MS-VDCT-01-2026',e.tramite||''],['Chacón Arce Roberto',e.solicitante||''],['4 151276-000',e.folio||'']]);let observationDone=false;for(const p of [...ps]){if(!p.parentNode)continue;let text=[...p.getElementsByTagNameNS(WNS,'t')].map(t=>t.textContent).join(''),norm=text.replace(/\s+/g,' ').trim();if(norm===':'){setParagraphText(p,'');continue}if(exact.has(norm)){setParagraphText(p,exact.get(norm));continue}if(!observationDone&&norm.includes('Según inspección de campo debe correr cerca del centro de calle a 8 metros')){replaceObservationParagraph(doc,p,obs);observationDone=true}}
 patchReasonTable(doc,defs);protectClosingBlocks(doc);return new XMLSerializer().serializeToString(doc)}
async function officeDocxBytes(e){let isRej=e.dictamen==='RECHAZADO',url=isRej?'./assets/templates/MACHOTE_RECHAZO_DEFINITIVO.docx':'./assets/templates/MACHOTE_APROBACION_DEFINITIVO.docx',src=new Uint8Array(await (await fetch(url)).arrayBuffer()),entries=await zipEntries(src),pp=presentationParts(e.presentacion,e);for(const ent of entries){if(ent.name==='word/document.xml'){let xml=dec.decode(ent.bytes);if(isRej)xml=patchRejectionBody(xml,e);else xml=replaceExactParagraphs(xml,[['09 de julio del 2026',dateEs(e.report?.fecha||e.fechaCalificacion?.slice(0,10)||e.fecha)],['MS-VDCT-01-2026',e.tramite||''],['2026',pp.tomo],['62146',pp.asiento],['1952.00 m²',e.area||''],['4 00227671-000',e.folio||''],['Las Horquetas',printedDistrict(e)]]);ent.bytes=enc.encode(xml)}else if(ent.name==='word/header1.xml'){let xml=dec.decode(ent.bytes);xml=replaceTextAcrossNodes(xml,'MS-VDCT-01-2026',e.tramite||'');ent.bytes=enc.encode(xml)}}return zipStore(entries)}
async function downloadOfficeWord(){let e=expedientes.find(x=>x.id===currentClose);if(!e||e.dictamen==='PENDIENTE'){alert('El expediente aún no tiene resolución final.');return}let bytes=await officeDocxBytes(e);blobDownload(bytes,`${safe(e.tramite||caseRef(e))}_${e.dictamen}.docx`,'application/vnd.openxmlformats-officedocument.wordprocessingml.document')}
window.downloadOfficeWord=downloadOfficeWord;

// Preview uses exactly the same raster pages as PDF generation, avoiding a second divergent layout.
function reportHtml(e){let data=JSON.stringify(e).replace(/</g,'\\u003c'),rej=e.dictamen==='RECHAZADO',paper=rej?'8.5in':'210mm';return `<!doctype html><html><head><meta charset="utf-8"><style>*{box-sizing:border-box}html,body{margin:0;background:#d9dee3;font-family:Arial,sans-serif}.wrap{padding:10px}.paper{display:block;width:${paper};height:auto;margin:0 auto 12px;background:#fff;box-shadow:0 1px 5px #8894}.status{padding:20px;text-align:center;color:#475569}@media print{body{background:#fff}.wrap{padding:0}.paper{margin:0;box-shadow:none;break-after:page;page-break-after:always}.paper:last-child{break-after:auto;page-break-after:auto}}</style></head><body><div class="wrap" id="pages"><div class="status">Preparando oficio...</div></div><script>(async()=>{try{const e=${data},cs=await parent.CVISADOS_EXPORTADORES.officeCanvases(e),host=document.getElementById('pages');host.innerHTML='';for(const c of cs){let im=document.createElement('img');im.className='paper';im.src=c.toDataURL('image/png');host.appendChild(im)}}catch(err){document.getElementById('pages').innerHTML='<div class="status">No fue posible preparar la vista previa.</div>'}})();<\/script></body></html>`}

async function loadImage(url){return new Promise((resolve,reject)=>{let i=new Image();i.onload=()=>resolve(i);i.onerror=reject;i.src=url})}
function newCanvas(w,h){let c=document.createElement('canvas');c.width=w;c.height=h;return c}
function wrapText(ctx,text,max){let words=String(text||'').split(/\s+/).filter(Boolean),lines=[],line='';for(const w of words){let test=line?line+' '+w:w;if(ctx.measureText(test).width>max&&line){lines.push(line);line=w}else line=test}if(line)lines.push(line);return lines.length?lines:['']}
function drawText(ctx,text,x,y,size,bold=false,color='#222',align='left'){ctx.font=`${bold?'700 ':'400 '}${size}px Arial`;ctx.fillStyle=color;ctx.textAlign=align;ctx.textBaseline='top';ctx.fillText(String(text||''),x,y)}
function drawWrapped(ctx,text,x,y,maxW,font=16,bold=false,color='#222',lh=1.3){ctx.font=`${bold?'700 ':'400 '}${font}px Arial`;ctx.fillStyle=color;ctx.textAlign='left';ctx.textBaseline='top';let lines=wrapText(ctx,text,maxW);lines.forEach((l,i)=>ctx.fillText(l,x,y+i*font*lh));return {lines,height:lines.length*font*lh}}
function reasonRowMetrics(ctx,item,index,maxW,font){ctx.font=`400 ${font}px Arial`;let L=wrapText(ctx,`${index}- ${stripSequencePrefix(item.motivation||item.detalle||'')}`,maxW),R=wrapText(ctx,`${index}- ${stripSequencePrefix(item.fund||'')}`,maxW),lineH=font*1.32;return {L,R,h:Math.max(L.length,R.length)*lineH+12,lineH}}
function fitReasonFont(ctx,item,index,maxW,maxH,start=17,min=9){for(let f=start;f>=min;f-=.5){let m=reasonRowMetrics(ctx,item,index,maxW,f);if(m.h<=maxH)return {font:f,...m}}return {font:min,...reasonRowMetrics(ctx,item,index,maxW,min)}}
function drawReasonHeader(ctx,img,y){let W=ctx.canvas.width,H=ctx.canvas.height,sy=.414*H,sh=.024*H;ctx.drawImage(img,.055*W,sy,.89*W,sh,.055*W,y,.89*W,sh)}
function drawReasonRows(ctx,items,startIndex,y,yLimit,font=15){let W=ctx.canvas.width,left=.062*W,mid=.505*W,maxW=.405*W,rowData=[],i=startIndex;ctx.strokeStyle='#173a5e';ctx.lineWidth=1.2;let headerY=y;drawReasonHeader(ctx,ctx.__templateImage,headerY);y+=.025*ctx.canvas.height;let bodyTop=y;for(;i<items.length;i++){let available=yLimit-y,m={font,...reasonRowMetrics(ctx,items[i],i+1,maxW,font)};if(m.h>available){if(rowData.length)break;m=fitReasonFont(ctx,items[i],i+1,maxW,available,font,8);if(m.h>available)break}rowData.push({i,m,y});y+=m.h}ctx.beginPath();ctx.rect(.055*W,headerY,.89*W,Math.max(y-bodyTop,1)+(.025*ctx.canvas.height));ctx.moveTo(.5*W,headerY);ctx.lineTo(.5*W,y);ctx.stroke();for(const r of rowData){ctx.font=`400 ${r.m.font}px Arial`;ctx.fillStyle='#222';ctx.textAlign='left';ctx.textBaseline='top';r.m.L.forEach((l,j)=>ctx.fillText(l,left,r.y+j*r.m.lineH));r.m.R.forEach((l,j)=>ctx.fillText(l,mid+8,r.y+j*r.m.lineH));if(r!==rowData[rowData.length-1]){ctx.beginPath();ctx.moveTo(.055*W,r.y+r.m.h-5);ctx.lineTo(.945*W,r.y+r.m.h-5);ctx.strokeStyle='rgba(23,58,94,.28)';ctx.stroke()}}return {next:i,y,headerY}}
function drawDynamicHeaderValues(ctx,e){let W=ctx.canvas.width,H=ctx.canvas.height;drawText(ctx,'OFICIO NÚMERO',.895*W,.081*H,13,true,'white','center');drawText(ctx,e.tramite,.895*W,.098*H,18,true,'white','center');drawText(ctx,'Fecha',.69*W,.151*H,21,true);drawText(ctx,dateEs(e.report?.fecha||e.fechaCalificacion?.slice(0,10)||e.fecha),.79*W,.151*H,21,true);drawText(ctx,'Trámite',.69*W,.177*H,21,true);drawText(ctx,e.tramite||'',.79*W,.177*H,21,true)}
function closingGeometry(ctx){let H=ctx.canvas.height;return {sy:.535*H,sh:.405*H,footerY:.95*H,gap:.012*H}}
function drawClosingBlock(ctx,img,destY){let W=ctx.canvas.width,H=ctx.canvas.height,{sy,sh,footerY}=closingGeometry(ctx),maxY=footerY-sh;let y=Math.max(.245*H,Math.min(destY,maxY));ctx.fillStyle='#fff';ctx.fillRect(0,y,W,sh);ctx.drawImage(img,0,sy,W,sh,0,y,W,sh);return {y,bottom:y+sh}}
function drawFooterCrop(ctx,img){let W=ctx.canvas.width,H=ctx.canvas.height,sy=.95*H,sh=.05*H;ctx.drawImage(img,0,sy,W,sh,0,sy,W,sh)}
function makeContinuationBase(img,e){let W=img.naturalWidth,H=img.naturalHeight,c=newCanvas(W,H),x=c.getContext('2d');x.fillStyle='#fff';x.fillRect(0,0,W,H);x.drawImage(img,0,0,W,.235*H,0,0,W,.235*H);drawDynamicHeaderValues(x,e);drawFooterCrop(x,img);x.__templateImage=img;return c}
function tryPlaceClosing(ctx,img,afterY){let {sh,footerY,gap}=closingGeometry(ctx),target=Math.max(.245*ctx.canvas.height,afterY+gap);if(target+sh<=footerY)return drawClosingBlock(ctx,img,target);return null}
function drawAdaptiveFirst(img,e,obs,items){let W=img.naturalWidth,H=img.naturalHeight,c=newCanvas(W,H),x=c.getContext('2d');x.drawImage(img,0,0,W,H);x.__templateImage=img;drawDynamicHeaderValues(x,e);drawText(x,e.solicitante||'',.515*W,.272*H,20,false);drawText(x,e.folio||'',.515*W,.294*H,20,false);
 // La zona variable se limpia para evitar restos del ejemplo y permitir flujo real.
 x.fillStyle='#fff';x.fillRect(0,.365*H,W,.585*H);drawFooterCrop(x,img);
 let y=.382*H,obsFont=18,max=.875*W;obs.forEach((v,i)=>{let r=drawWrapped(x,`${i+1}. ${v}`,.055*W,y,max,obsFont,false,'#222',1.28);y+=r.height+8});let tableY=Math.max(.455*H,y+14),res=drawReasonRows(x,items,0,tableY,.91*H,18),closed=false;if(res.next===items.length)closed=!!tryPlaceClosing(x,img,res.y);return {canvas:c,next:res.next,endY:res.y,closingPlaced:closed}}
function makeClosingPage(img,e){let c=makeContinuationBase(img,e),x=c.getContext('2d');drawClosingBlock(x,img,.255*c.height);return c}
async function officeCanvases(e){let rej=e.dictamen==='RECHAZADO',img=await loadImage(rej?'./assets/templates/OFICIAL_RECHAZO_FONDO.png':'./assets/templates/OFICIAL_APROBACION_FONDO.png');if(!rej){let c=newCanvas(img.naturalWidth,img.naturalHeight),x=c.getContext('2d'),W=c.width,H=c.height;x.drawImage(img,0,0,W,H);let pp=presentationParts(e.presentacion,e);drawText(x,e.tramite,.895*W,.09*H,17,true,'white','center');drawText(x,dateEs(e.report?.fecha||e.fechaCalificacion?.slice(0,10)||e.fecha),.742*W,.147*H,20,true);drawText(x,e.tramite,.75*W,.178*H,20,true);[[pp.tomo,.135],[pp.asiento,.31],[e.area,.505],[e.folio,.695],[printedDistrict(e),.865]].forEach(([v,p])=>drawText(x,v,p*W,.472*H,19,true,'#222','center'));return [c]}
 let obs=rejectionObservationItems(e),items=allRejectReasons(e);if(!obs.length)obs=['Sin observaciones adicionales.'];if(!items.length)items=[{motivation:'Sin motivación técnica registrada.',fund:''}];let pages=[],first=drawAdaptiveFirst(img,e,obs,items);pages.push(first.canvas);let idx=first.next,closingPlaced=first.closingPlaced;while(idx<items.length){let c=makeContinuationBase(img,e),x=c.getContext('2d'),res=drawReasonRows(x,items,idx,.28*c.height,.90*c.height,18);if(res.next===items.length)closingPlaced=!!tryPlaceClosing(x,img,res.y);pages.push(c);if(res.next===idx)break;idx=res.next}if(!closingPlaced)pages.push(makeClosingPage(img,e));return pages}
async function officeCanvas(e){let pages=await officeCanvases(e);return pages[0]}
async function canvasJpeg(c){return new Uint8Array(await (await fetch(c.toDataURL('image/jpeg',.95))).arrayBuffer())}
function pdfFromJpegs(jpegs,pageW,pageH){let N=jpegs.length,objs=[],add=s=>{objs.push(typeof s==='string'?enc.encode(s):s);return objs.length},imgIds=[],contentIds=[];for(const j of jpegs)imgIds.push(add(concat([enc.encode(`<< /Type /XObject /Subtype /Image /Width ${j.w} /Height ${j.h} /ColorSpace /DeviceRGB /BitsPerComponent 8 /Filter /DCTDecode /Length ${j.bytes.length} >>\nstream\n`),j.bytes,enc.encode('\nendstream')])));for(let i=0;i<N;i++){let stream=enc.encode(`q\n${pageW} 0 0 ${pageH} 0 0 cm\n/Im${i} Do\nQ\n`);contentIds.push(add(concat([enc.encode(`<< /Length ${stream.length} >>\nstream\n`),stream,enc.encode('endstream')])))}let pageStart=objs.length+1,pagesRootId=pageStart+N;for(let i=0;i<N;i++)add(`<< /Type /Page /Parent ${pagesRootId} 0 R /MediaBox [0 0 ${pageW} ${pageH}] /Resources << /XObject << /Im${i} ${imgIds[i]} 0 R >> >> /Contents ${contentIds[i]} 0 R >>`);let kids=Array.from({length:N},(_,i)=>`${pageStart+i} 0 R`).join(' '),pagesId=add(`<< /Type /Pages /Kids [${kids}] /Count ${N} >>`),catalog=add(`<< /Type /Catalog /Pages ${pagesId} 0 R >>`);return finishPdf(objs,catalog)}
function finishPdf(objs,catalog){let parts=[enc.encode('%PDF-1.7\n%âãÏÓ\n')],offset=[0],pos=parts[0].length;objs.forEach((o,i)=>{offset[i+1]=pos;let p=concat([enc.encode(`${i+1} 0 obj\n`),o,enc.encode('\nendobj\n')]);parts.push(p);pos+=p.length});let xref=pos,s=`xref\n0 ${objs.length+1}\n0000000000 65535 f \n`+offset.slice(1).map(v=>String(v).padStart(10,'0')+' 00000 n \n').join('')+`trailer\n<< /Size ${objs.length+1} /Root ${catalog} 0 R >>\nstartxref\n${xref}\n%%EOF`;parts.push(enc.encode(s));return concat(parts)}
function interactivePdf(jpegs,pageW,pageH,fields=[]){let N=jpegs.length,F=fields.length,objs=[],add=s=>{objs.push(typeof s==='string'?enc.encode(s):s);return objs.length},imgIds=[],contentIds=[];for(const j of jpegs)imgIds.push(add(concat([enc.encode(`<< /Type /XObject /Subtype /Image /Width ${j.w} /Height ${j.h} /ColorSpace /DeviceRGB /BitsPerComponent 8 /Filter /DCTDecode /Length ${j.bytes.length} >>\nstream\n`),j.bytes,enc.encode('\nendstream')])));for(let i=0;i<N;i++){let stream=enc.encode(`q\n${pageW} 0 0 ${pageH} 0 0 cm\n/Im${i} Do\nQ\n`);contentIds.push(add(concat([enc.encode(`<< /Length ${stream.length} >>\nstream\n`),stream,enc.encode('endstream')])))}let fieldIds=[];for(const f of fields)fieldIds.push(add(`<< /Type /Annot /Subtype /Widget /FT /Tx /T (${String(f.name).replace(/[()]/g,'')}) /Rect [${f.x} ${f.y} ${f.x+f.w} ${f.y+f.h}] /F 4 /V () /DA (/Helv 9 Tf 0 g) >>`));let pageStart=objs.length+1,pagesRootId=pageStart+N;for(let i=0;i<N;i++){let anns=fields.map((f,k)=>({f,id:fieldIds[k]})).filter(x=>(x.f.page??N-1)===i).map(x=>x.id+' 0 R').join(' ');add(`<< /Type /Page /Parent ${pagesRootId} 0 R /MediaBox [0 0 ${pageW} ${pageH}] /Resources << /XObject << /Im${i} ${imgIds[i]} 0 R >> /Font << /Helv << /Type /Font /Subtype /Type1 /BaseFont /Helvetica >> >> >> /Contents ${contentIds[i]} 0 R${anns?` /Annots [${anns}]`:''} >>`)}let kids=Array.from({length:N},(_,i)=>`${pageStart+i} 0 R`).join(' '),pagesId=add(`<< /Type /Pages /Kids [${kids}] /Count ${N} >>`),acro=add(`<< /Fields [${fieldIds.map(i=>i+' 0 R').join(' ')}] /DA (/Helv 9 Tf 0 g) >>`),catalog=add(`<< /Type /Catalog /Pages ${pagesId} 0 R /AcroForm ${acro} 0 R >>`);return finishPdf(objs,catalog)}
function pdfFields(e,pageCount=1){let last=pageCount-1;return e.dictamen==='RECHAZADO'?[{name:'Observaciones adicionales',x:35,y:500,w:540,h:48,page:0},{name:'Recibido por',x:45,y:100,w:280,h:18,page:last},{name:'Cedula',x:390,y:100,w:165,h:18,page:last},{name:'Firma',x:45,y:78,w:280,h:18,page:last},{name:'Fecha recibido',x:390,y:78,w:165,h:18,page:last}]:[{name:'Firma',x:50,y:95,w:260,h:22,page:0}]}
async function downloadOfficePdf(editable=false){let e=expedientes.find(x=>x.id===currentClose);if(!e||e.dictamen==='PENDIENTE'){alert('El expediente aún no tiene resolución final.');return}let cs=await officeCanvases(e),jpegs=[];for(const c of cs)jpegs.push({bytes:await canvasJpeg(c),w:c.width,h:c.height});let isRej=e.dictamen==='RECHAZADO',pageW=isRej?612:595,pageH=isRej?792:842,pdf=editable?interactivePdf(jpegs,pageW,pageH,pdfFields(e,cs.length)):pdfFromJpegs(jpegs,pageW,pageH);blobDownload(pdf,`${safe(e.tramite||caseRef(e))}_${e.dictamen}${editable?'_EDITABLE':''}.pdf`,'application/pdf')}
window.downloadOfficePdf=downloadOfficePdf;

window.CVISADOS_EXPORTADORES={version:VERSION,presentationParts,zipStore,gestionXlsxBytes,officeDocxBytes,patchRejectionBody,officeCanvases,officeCanvas,canvasJpeg,pdfFromJpegs,interactivePdf,pdfFields,reportHtml};
renderGestion();refreshReport();
})();
