(() => {
'use strict';
const VERSION='3.6.0';
const enc=new TextEncoder(), dec=new TextDecoder();
let gestionSelectedId=null;
const q=id=>document.getElementById(id);
function xmlEscape(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[c]))}
function stripSequencePrefix(v){return String(v??'').replace(/^\s*\d+\s*[-.)]\s*/, '').trim()}
function presentationParts(value,fallback={}){let s=String(value||'').trim(),m=s.match(/^(\d{4})\s*-\s*(\d+)(?:\s*-\s*C)?$/i);return m?{tomo:m[1],asiento:m[2]}:{tomo:String(fallback.tomo||''),asiento:String(fallback.asiento||'')}}
function moduleCase(module){let id={tramites:currentPre,pre:currentPre,inspection:currentInspection,calificacion:currentMotor,cierre:currentClose,gestion:gestionSelectedId}[module];return expedientes.find(x=>x.id===Number(id))||expedientes.find(x=>!x.finalizado)||expedientes[0]||null}
function appendModuleObservation(e,module){if(!e)return;let label={tramites:'Trámites',pre:'Precalificación',inspection:'Inspección',calificacion:'Calificación',cierre:'Resoluciones',gestion:'Gestión'}[module]||module,stamp=new Date().toLocaleString('es-CR'),text=`${label}: datos guardados y avance registrado.`;e.observaciones=String(e.observaciones||'').trim();e.observaciones=e.observaciones?`${e.observaciones}\n${text}`:text;e.observacionesHistorial=Array.isArray(e.observacionesHistorial)?e.observacionesHistorial:[];e.observacionesHistorial.push({modulo:label,observacion:text,fecha:new Date().toISOString()});return text}
function silentSave(module,e){if(!e)return;
 if(module==='pre'){Object.entries(COND_FIELDS).forEach(([key,id])=>e.cond[key]=!!q(id)?.checked);updateDecision(e)}
 if(module==='inspection'){e.inspection.observaciones=q('inspectionObs')?.value||e.inspection.observaciones||'';e.inspection.guardada=true;let first=e.inspection.accesos[0]||emptyAccess();e.inspection.anchoCallePlanoMadre=first.anchoPlano;e.inspection.anchoCalleInspeccion=first.anchoInspeccion;e.inspection.referenciaMedicion=first.referencia;e.inspection.distanciaDesdeLC=first.desdeLC;e.inspection.distanciaDesdeLCInspeccion=first.desdeLCInspeccion;e.inspection.acceso=first.tipo;e.inspection.diferenciaAncho=accessEval(first).difference;updateDecision(e);e.estado=e.dictamen==='PENDIENTE'?'EN INSPECCIÓN':'LISTO PARA CALIFICACIÓN'}
 if(module==='calificacion'){e.calificacionEncargado=q('calificador')?.value.trim()||e.calificacionEncargado||'';e.fechaCalificacion=new Date().toISOString();updateDecision(e)}
 if(module==='cierre'){saveReportFieldsSilent(e)}
 appendModuleObservation(e,module);persist();renderAll()}
function nextModule(module){let e=moduleCase(module);silentSave(module,e);let next={tramites:'pre',pre:'inspection',inspection:'calificacion',calificacion:'cierre',cierre:'gestion',gestion:'tramites'}[module]||'tramites';go(next)}
window.nextModule=nextModule;

function renderGestion(){let body=q('gestionBody');if(!body)return;let s=foldName(q('gSearch')?.value||''),estado=q('gEstado')?.value||'',res=q('gResultado')?.value||'',dist=q('gDistrito')?.value||'';
 let estados=[...new Set(expedientes.map(e=>e.estado).filter(Boolean))].sort(),districts=[...new Set(expedientes.map(e=>e.distrito||'Sin distrito'))].sort();let es=q('gEstado'),ds=q('gDistrito');if(es){let old=es.value;es.innerHTML='<option value="">Todos</option>'+estados.map(v=>`<option>${esc(v)}</option>`).join('');es.value=old}if(ds){let old=ds.value;ds.innerHTML='<option value="">Todos</option>'+districts.map(v=>`<option>${esc(v)}</option>`).join('');ds.value=old}
 let rows=expedientes.filter(e=>(!s||foldName([e.tramite,e.folio,e.presentacion,e.solicitante,e.lugar,e.distrito].join(' ')).includes(s))&&(!estado||e.estado===estado)&&(!res||e.dictamen===res)&&(!dist||(e.distrito||'Sin distrito')===dist));q('gestionSummary').textContent=`${rows.length} de ${expedientes.length} trámites`;body.innerHTML=rows.length?rows.map(e=>{let a=ageInfo(e),sel=e.id===gestionSelectedId?' selected':'';return `<tr class="click${sel}" onclick="selectGestion(${e.id})"><td><b>${esc(e.tramite||caseRef(e))}</b></td><td>${esc(e.fecha||'')}<div><span class="pill ${a.className||'blue'}">${esc(a.label)}</span></div></td><td>${esc(e.folio||'')}</td><td>${esc(e.presentacion||'')}</td><td>${esc(e.solicitante||'')}</td><td>${esc(e.distrito||'Sin distrito')}<div class="small">${esc(e.lugar||'')}</div></td><td>${statusPill(e)}</td><td><span class="pill ${e.dictamen==='RECHAZADO'?'red':e.dictamen==='APROBADO'?'green':'amber'}">${esc(e.dictamen||'PENDIENTE')}</span></td><td>${esc(e.observaciones||'')}</td></tr>`}).join(''):'<tr><td colspan="9" class="empty">Sin resultados</td></tr>';}
function selectGestion(id){gestionSelectedId=Number(id);let e=expedientes.find(x=>x.id===gestionSelectedId);q('gestionSelected').textContent=e?`Seleccionado: ${caseRef(e)}`:'Seleccione una fila para registrar la observación de Gestión.';renderGestion()}
function clearGestionFilters(){['gSearch','gEstado','gResultado','gDistrito'].forEach(id=>{if(q(id))q(id).value=''});renderGestion()}
window.renderGestion=renderGestion;window.selectGestion=selectGestion;window.clearGestionFilters=clearGestionFilters;
['gSearch','gEstado','gResultado','gDistrito'].forEach(id=>{let el=q(id);if(el)el.addEventListener(id==='gSearch'?'input':'change',renderGestion)});

// ZIP helpers (STORE writer + existing app reader for deflate/store).
const CRC_TABLE=(()=>{let t=new Uint32Array(256);for(let n=0;n<256;n++){let c=n;for(let k=0;k<8;k++)c=(c&1)?0xedb88320^(c>>>1):c>>>1;t[n]=c>>>0}return t})();
function crc32(bytes){let c=0xffffffff;for(const b of bytes)c=CRC_TABLE[(c^b)&255]^(c>>>8);return (c^0xffffffff)>>>0}
function u16(v){return [v&255,(v>>>8)&255]} function u32(v){return [v&255,(v>>>8)&255,(v>>>16)&255,(v>>>24)&255]}
function concat(parts){let len=parts.reduce((n,p)=>n+p.length,0),out=new Uint8Array(len),o=0;for(const p of parts){out.set(p,o);o+=p.length}return out}
function zipStore(entries){let local=[],central=[],offset=0;for(const ent of entries){let name=enc.encode(ent.name),data=ent.bytes instanceof Uint8Array?ent.bytes:new Uint8Array(ent.bytes),crc=crc32(data),lh=new Uint8Array([...u32(0x04034b50),...u16(20),...u16(0x800),...u16(0),...u16(0),...u16(0),...u32(crc),...u32(data.length),...u32(data.length),...u16(name.length),...u16(0),...name]);local.push(lh,data);let ch=new Uint8Array([...u32(0x02014b50),...u16(20),...u16(20),...u16(0x800),...u16(0),...u16(0),...u16(0),...u32(crc),...u32(data.length),...u32(data.length),...u16(name.length),...u16(0),...u16(0),...u16(0),...u16(0),...u32(0),...u32(offset),...name]);central.push(ch);offset+=lh.length+data.length}let c=concat(central),l=concat(local),end=new Uint8Array([...u32(0x06054b50),...u16(0),...u16(0),...u16(entries.length),...u16(entries.length),...u32(c.length),...u32(l.length),...u16(0)]);return concat([l,c,end])}
function identifiersFromName(name){let t=(name.match(/(?:VMSDC|MS-VDCT)[ _-]*\d{2,4}[ _-]*\d{1,10}/i)||[])[0]||'',f=(name.match(/\b\d{1,2}[ _-]\d{5,10}[ _-]\d{3}\b/)||[])[0]||'',p=(name.match(/\b\d{4}[ _-]\d{3,10}(?:[ _-]C)?\b/i)||[])[0]||'';return {tramite:t.replace(/_/g,' ').trim(),folio:f.replace(/_/g,'-').trim(),presentacion:p.replace(/_/g,'-').trim()}}
function attachMeta(e,name,type,size,zipName,ids){if(!e)return;e.archivosAdjuntos=Array.isArray(e.archivosAdjuntos)?e.archivosAdjuntos:[];let key=`${zipName}|${name}`;if(!e.archivosAdjuntos.some(x=>x.clave===key))e.archivosAdjuntos.push({clave:key,nombre:name,tipo:type,tamano:size,origenZip:zipName,identificadores:ids,fecha:new Date().toISOString()})}
async function importZip(files){let stats=statsNew();stats.files=files.length;let attachments=0;for(const zf of files){try{let zb=new Uint8Array(await zf.arrayBuffer()),dir=zipDirectory(zb);for(const [name,entry] of Object.entries(dir)){if(name.endsWith('/'))continue;let bytes=await unzipEntry(zb,entry),lower=name.toLowerCase(),file=new File([bytes],name,{type:'application/octet-stream'}),results=[];
  try{if(lower.endsWith('.json')){let v=JSON.parse(dec.decode(bytes));for(const r of jsonImportRows(v))results.push(upsertImported(r,{name:`${zf.name}/${name}`,type:'ZIP-JSON'}))}
  else if(lower.endsWith('.csv')){let parsed=parseCsv(dec.decode(bytes));for(const r of parsed.rows||[])results.push(upsertImported(r,{name:`${zf.name}/${name}`,type:'ZIP-CSV'}))}
  else if(lower.endsWith('.xlsx')){let parsed=await parseXlsx(file);for(const r of parsed.rows||[])results.push(upsertImported(r,{name:`${zf.name}/${name}`,type:'ZIP-Excel'}))}
  else if(lower.endsWith('.pdf')){let text=await pdfStrings(bytes),r=pdfRecord(text);if(hasIdentifier(mapHeaders(r)))results.push(upsertImported(r,{name:`${zf.name}/${name}`,type:'ZIP-PDF'}))}
  }catch(err){console.warn('Archivo interno no interpretado',name,err)}
  results.forEach(r=>statsAdd(stats,r));let ids=identifiersFromName(name),target=null;for(const r of results){if(r?.id){target=expedientes.find(e=>e.id===r.id);if(target)break}}if(!target&&hasIdentifier(mapHeaders(ids))){let ms=findIdentifierMatches(mapHeaders(ids));target=ms[0]||null}if(target){attachMeta(target,name,lower.split('.').pop().toUpperCase(),bytes.length,zf.name,ids);attachments++}
 }
 }catch(err){stats.skipped++;stats.warnings.push(`${zf.name}: ${err.message}`)}}persist();renderAll();q('importMsg').textContent=`ZIP: ${stats.new} nuevo(s) · ${stats.updated} actualizado(s) · ${stats.assigned} X→trámite asignado(s) · ${attachments} archivo(s) enlazado(s)`}
window.importZip=importZip;let zinput=q('fileZip');if(zinput)zinput.onchange=e=>importZip([...e.target.files]);

// XLSX export with one sheet and a JSON-full-data column.
function colName(n){let s='';for(n++;n;n=Math.floor((n-1)/26))s=String.fromCharCode(65+(n-1)%26)+s;return s}
function xlsxCell(v,r,c){let ref=colName(c)+(r+1);if(typeof v==='number')return `<c r="${ref}"><v>${v}</v></c>`;return `<c r="${ref}" t="inlineStr"><is><t xml:space="preserve">${xmlEscape(v??'')}</t></is></c>`}
function gestionXlsxBytes(){let headers=['Trámite','Fecha solicitud','Folio real','Plano','Presentación','Tomo','Asiento','Área','Solicitante','Correo','Distrito','Lugar','Tipo ingreso','Modalidad','Responsable','Estado','Resultado','Finalizado','Observaciones','Archivos adjuntos','Información completa JSON'],rows=expedientes.map(e=>{let pp=presentationParts(e.presentacion,e);return [e.tramite,e.fecha,e.folio,e.plano,e.presentacion,pp.tomo,pp.asiento,e.area,e.solicitante,e.correo,e.distrito,e.lugar,e.ingreso,e.modalidad,e.responsable,e.estado,e.dictamen,e.finalizado?'Sí':'No',e.observaciones,(e.archivosAdjuntos||[]).map(x=>x.nombre).join(' | '),JSON.stringify(e)]});let all=[headers,...rows],sheetRows=all.map((row,r)=>`<row r="${r+1}">${row.map((v,c)=>xlsxCell(v,r,c)).join('')}</row>`).join(''),sheet=`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetViews><sheetView workbookViewId="0"><pane ySplit="1" topLeftCell="A2" activePane="bottomLeft" state="frozen"/></sheetView></sheetViews><sheetData>${sheetRows}</sheetData><autoFilter ref="A1:U${all.length}"/></worksheet>`,wb=`<?xml version="1.0" encoding="UTF-8"?><workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets><sheet name="Trámites" sheetId="1" r:id="rId1"/></sheets></workbook>`,rels=`<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/></Relationships>`,rootrels=`<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>`,ct=`<?xml version="1.0" encoding="UTF-8"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/></Types>`;return zipStore([{name:'[Content_Types].xml',bytes:enc.encode(ct)},{name:'_rels/.rels',bytes:enc.encode(rootrels)},{name:'xl/workbook.xml',bytes:enc.encode(wb)},{name:'xl/_rels/workbook.xml.rels',bytes:enc.encode(rels)},{name:'xl/worksheets/sheet1.xml',bytes:enc.encode(sheet)}])}
function blobDownload(bytes,name,type){let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([bytes],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1500)}
function exportGestionExcel(){blobDownload(gestionXlsxBytes(),`C_VISADOS_GESTION_${new Date().toISOString().slice(0,10)}.xlsx`,'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet')}
window.exportGestionExcel=exportGestionExcel;

// Definitive office template patching.
async function zipEntries(bytes){let dir=zipDirectory(bytes),out=[];for(const name of Object.keys(dir))out.push({name,bytes:await unzipEntry(bytes,dir[name])});return out}
function setParagraphText(p,newText){let ts=[...p.getElementsByTagNameNS('*','t')];if(!ts.length)return false;ts[0].textContent=newText;for(let i=1;i<ts.length;i++)ts[i].textContent='';let space='http://www.w3.org/XML/1998/namespace';if(/^\s|\s$/.test(newText))ts[0].setAttributeNS(space,'xml:space','preserve');return true}
function replaceExactParagraphs(xml,repls,removeColon=false){let doc=new DOMParser().parseFromString(xml,'application/xml'),ps=[...doc.getElementsByTagNameNS('*','p')];for(const p of ps){let ts=[...p.getElementsByTagNameNS('*','t')],text=ts.map(t=>t.textContent).join('');let norm=text.replace(/\s+/g,' ').trim();if(removeColon&&norm===':'){setParagraphText(p,'');continue}for(const [oldv,newv] of repls){if(norm===String(oldv).replace(/\s+/g,' ').trim()){setParagraphText(p,String(newv??''));break}}}return new XMLSerializer().serializeToString(doc)}
function replaceCellParagraphs(xml,oldv,newv){return replaceExactParagraphs(xml,[[oldv,newv]])}
function replaceTextAcrossNodes(xml,oldv,newv){let doc=new DOMParser().parseFromString(xml,'application/xml'),ps=[...doc.getElementsByTagNameNS('*','p')];for(const p of ps){let ts=[...p.getElementsByTagNameNS('*','t')],vals=ts.map(t=>t.textContent||''),joined=vals.join(''),start=joined.indexOf(oldv);if(start<0)continue;let end=start+oldv.length,pos=0,first=true;for(let i=0;i<ts.length;i++){let v=vals[i],a=pos,b=pos+v.length;pos=b;if(b<=start||a>=end)continue;let left=start>a?v.slice(0,start-a):'',right=end<b?v.slice(end-a):'';ts[i].textContent=left+(first?String(newv??''):'')+right;first=false}break}return new XMLSerializer().serializeToString(doc)}
function addLineBreakText(p,items,prefix=true){let ts=[...p.getElementsByTagNameNS('*','t')];if(!ts.length)return;let r=ts[0].parentNode;while(r.firstChild)r.removeChild(r.firstChild);items.forEach((v,i)=>{if(i){let br=p.ownerDocument.createElementNS('http://schemas.openxmlformats.org/wordprocessingml/2006/main','w:br');r.appendChild(br)}let t=p.ownerDocument.createElementNS('http://schemas.openxmlformats.org/wordprocessingml/2006/main','w:t');t.textContent=`${prefix?i+1+'- ':''}${v}`;r.appendChild(t)});}
function patchRejectionBody(xml,e){let doc=new DOMParser().parseFromString(xml,'application/xml'),ps=[...doc.getElementsByTagNameNS('*','p')],defs=allRejectReasons(e),obs=rejectionObservationItems(e);const exact=new Map([['09 de julio del 2026',dateEs(e.report?.fecha||e.fecha)],['MS-VDCT-01-2026',e.tramite||''],['Chacón Arce Roberto',e.solicitante||''],['4 151276-000',e.folio||'']]);for(const p of ps){let text=[...p.getElementsByTagNameNS('*','t')].map(t=>t.textContent).join(''),norm=text.replace(/\s+/g,' ').trim();if(norm===':'){setParagraphText(p,'');continue}if(exact.has(norm)){setParagraphText(p,exact.get(norm));continue}if(norm.includes('Según inspección de campo debe correr cerca del centro de calle a 8 metros')){addLineBreakText(p,obs.length?obs:['Sin observaciones adicionales.'],false); // manually prefix periods
 let ts=[...p.getElementsByTagNameNS('*','t')]; if(ts.length){ // rewrite to dot numbering
   let r=ts[0].parentNode; while(r.firstChild)r.removeChild(r.firstChild);(obs.length?obs:['Sin observaciones adicionales.']).forEach((v,i)=>{if(i)r.appendChild(doc.createElementNS('http://schemas.openxmlformats.org/wordprocessingml/2006/main','w:br'));let t=doc.createElementNS('http://schemas.openxmlformats.org/wordprocessingml/2006/main','w:t');t.textContent=`${i+1}. ${v}`;r.appendChild(t)}) }
 }}let tables=[...doc.getElementsByTagNameNS('*','tbl')];if(tables[3]){let rows=[...tables[3].getElementsByTagNameNS('*','tr')],cells=rows[1]?[...rows[1].getElementsByTagNameNS('*','tc')]:[];if(cells.length>=2){let lp=[...cells[0].getElementsByTagNameNS('*','p')][0],rp=[...cells[1].getElementsByTagNameNS('*','p')][0],items=defs.length?defs:[{motivation:'Sin motivación técnica registrada.',fund:''}];addLineBreakText(lp,items.map(x=>stripSequencePrefix(x.motivation||x.detalle||'')));addLineBreakText(rp,items.map(x=>stripSequencePrefix(x.fund||'')));}}return new XMLSerializer().serializeToString(doc)}
async function officeDocxBytes(e){let isRej=e.dictamen==='RECHAZADO',url=isRej?'./assets/templates/MACHOTE_RECHAZO_DEFINITIVO.docx':'./assets/templates/MACHOTE_APROBACION_DEFINITIVO.docx',src=new Uint8Array(await (await fetch(url)).arrayBuffer()),entries=await zipEntries(src),pp=presentationParts(e.presentacion,e);for(const ent of entries){if(ent.name==='word/document.xml'){let xml=dec.decode(ent.bytes);if(isRej)xml=patchRejectionBody(xml,e);else xml=replaceExactParagraphs(xml,[['09 de julio del 2026',dateEs(e.report?.fecha||e.fecha)],['MS-VDCT-01-2026',e.tramite||''],['2026',pp.tomo],['62146',pp.asiento],['1952.00 m²',e.area||''],['4 00227671-000',e.folio||''],['Las Horquetas',printedDistrict(e)]]);ent.bytes=enc.encode(xml)}else if(ent.name==='word/header1.xml'){let xml=dec.decode(ent.bytes);xml=replaceTextAcrossNodes(xml,'MS-VDCT-01-2026',e.tramite||'');ent.bytes=enc.encode(xml)}}
 return zipStore(entries)}
async function downloadOfficeWord(){let e=expedientes.find(x=>x.id===currentClose);if(!e||e.dictamen==='PENDIENTE'){alert('El expediente aún no tiene resolución final.');return}let bytes=await officeDocxBytes(e);blobDownload(bytes,`${safe(e.tramite||caseRef(e))}_${e.dictamen}.docx`,'application/vnd.openxmlformats-officedocument.wordprocessingml.document')}
window.downloadOfficeWord=downloadOfficeWord;

// Office preview and PDF: definitive-template background + dynamic overlays.
function reportHtml(e){let rej=e.dictamen==='RECHAZADO',pp=presentationParts(e.presentacion,e),obs=rejectionObservationItems(e),defs=allRejectReasons(e),bg=rej?'./assets/templates/OFICIAL_RECHAZO_FONDO.png':'./assets/templates/OFICIAL_APROBACION_FONDO.png';if(!rej)return `<!doctype html><html><head><meta charset="utf-8"><style>@page{size:A4;margin:0}*{box-sizing:border-box}html,body{margin:0;background:#ddd;font-family:Arial}.p{width:210mm;height:297mm;position:relative;margin:auto;background:white;overflow:hidden}.bg{position:absolute;inset:0;width:100%;height:100%}.x{position:absolute;font-weight:700;color:#222}.office{left:82.5%;top:9.0%;width:14%;font-size:10.5pt;text-align:center;color:white}.date{left:73.8%;top:14.6%;font-size:12pt}.tr{left:74.8%;top:17.7%;font-size:12pt}.c{top:48.2%;font-size:11pt;text-align:center}.tomo{left:5.4%;width:16%}.asi{left:21.4%;width:19%}.area{left:40.5%;width:19%}.folio{left:59.7%;width:20%}.dist{left:79.5%;width:15%}</style></head><body><div class="p"><img class="bg" src="${bg}"><div class="x office">${esc(e.tramite||'')}</div><div class="x date">${esc(dateEs(e.report?.fecha||e.fecha))}</div><div class="x tr">${esc(e.tramite||'')}</div><div class="x c tomo">${esc(pp.tomo)}</div><div class="x c asi">${esc(pp.asiento)}</div><div class="x c area">${esc(e.area||'')}</div><div class="x c folio">${esc(e.folio||'')}</div><div class="x c dist">${esc(printedDistrict(e))}</div></div></body></html>`;
 let reasonRows=(defs.length?defs:[{motivation:'Sin motivación técnica registrada.',fund:''}]).map((x,i)=>`<div class="rr"><div><b>${i+1}-</b> ${esc(stripSequencePrefix(x.motivation||x.detalle||''))}</div><div><b>${i+1}-</b> ${esc(stripSequencePrefix(x.fund||''))}</div></div>`).join(''),obsRows=(obs.length?obs:['Sin observaciones adicionales.']).map((v,i)=>`<div><b>${i+1}.</b> ${esc(v)}</div>`).join('');return `<!doctype html><html><head><meta charset="utf-8"><style>@page{size:A4;margin:0}*{box-sizing:border-box}html,body{margin:0;background:#ddd;font-family:Arial}.p{width:210mm;height:297mm;position:relative;margin:auto;background:#fff;overflow:hidden}.bg{position:absolute;inset:0;width:100%;height:100%}.x{position:absolute;color:#222}.office{left:82.2%;top:9.0%;width:14%;font-size:10.5pt;text-align:center;color:white;font-weight:700}.date{left:79.0%;top:15.0%;font-size:12pt;font-weight:700}.tr{left:79.0%;top:17.55%;font-size:12pt;font-weight:700}.sol{left:36.6%;top:26.9%;font-size:10.5pt}.fol{left:36.6%;top:29.1%;font-size:10.5pt}.obs{left:4.5%;top:36.4%;width:91%;font-size:9.5pt;line-height:1.35}.reasons{left:4.5%;top:43.4%;width:91%;height:9.0%;display:flex;flex-direction:column;justify-content:flex-start;font-size:9pt;line-height:1.25;overflow:hidden}.rr{display:grid;grid-template-columns:1fr 1fr;gap:7mm;border-bottom:0;padding:0 1.2mm 1.3mm}.rr>div{min-width:0}.smallmany{font-size:7.5pt}</style></head><body><div class="p"><img class="bg" src="${bg}"><div class="x office">${esc(e.tramite||'')}</div><div class="x date">${esc(dateEs(e.report?.fecha||e.fecha))}</div><div class="x tr">${esc(e.tramite||'')}</div><div class="x sol">${esc(e.solicitante||'')}</div><div class="x fol">${esc(e.folio||'')}</div><div class="x obs">${obsRows}</div><div class="x reasons ${defs.length>3?'smallmany':''}">${reasonRows}</div></div></body></html>`}

async function loadImage(url){return new Promise((resolve,reject)=>{let i=new Image();i.onload=()=>resolve(i);i.onerror=reject;i.src=url})}
function wrapText(ctx,text,max){let words=String(text||'').split(/\s+/),lines=[],line='';for(const w of words){let test=line?line+' '+w:w;if(ctx.measureText(test).width>max&&line){lines.push(line);line=w}else line=test}if(line)lines.push(line);return lines}
async function officeCanvas(e,blankForFields=false){
 let rej=e.dictamen==='RECHAZADO',img=await loadImage(rej?'./assets/templates/OFICIAL_RECHAZO_FONDO.png':'./assets/templates/OFICIAL_APROBACION_FONDO.png'),c=document.createElement('canvas');c.width=img.naturalWidth;c.height=img.naturalHeight;let x=c.getContext('2d');x.drawImage(img,0,0,c.width,c.height);
 let text=(t,px,py,size,bold=false,color='#222',align='left')=>{x.font=`${bold?'700 ':'400 '}${size}px Arial`;x.fillStyle=color;x.textAlign=align;x.textBaseline='top';x.fillText(String(t||''),px*c.width,py*c.height)};
 if(!rej){let pp=presentationParts(e.presentacion,e);text(e.tramite,.895,.09,17,true,'white','center');text(dateEs(e.report?.fecha||e.fecha),.742,.147,20,true);text(e.tramite,.75,.178,20,true);[[pp.tomo,.135],[pp.asiento,.31],[e.area,.505],[e.folio,.695],[printedDistrict(e),.865]].forEach(([v,p])=>text(v,p,.472,19,true,'#222','center'));return c}
 text(e.tramite,.895,.09,17,true,'white','center');text(dateEs(e.report?.fecha||e.fecha),.79,.151,21,true);text(e.tramite||'',.79,.177,21,true);text(e.solicitante||'',.365,.272,18,false);text(e.folio||'',.365,.294,18,false);
 let obs=rejectionObservationItems(e),defs=allRejectReasons(e),obsItems=obs.length?obs:['Sin observaciones adicionales.'];x.fillStyle='#222';x.textAlign='left';x.textBaseline='top';
 let obsFont=17,obsTop=.375*c.height,obsBottom=.410*c.height,obsMax=.88*c.width,obsLines=[];
 for(;obsFont>=9;obsFont-=.5){x.font=`${obsFont}px Arial`;obsLines=obsItems.map((v,i)=>wrapText(x,`${i+1}. ${v}`,obsMax));let needed=obsLines.reduce((n,a)=>n+a.length,0)*obsFont*1.28+(obsLines.length-1)*3;if(needed<=obsBottom-obsTop)break}
 x.font=`${obsFont}px Arial`;let oy=obsTop,olh=obsFont*1.28;obsLines.forEach(lines=>{lines.forEach(l=>{x.fillText(l,.045*c.width,oy);oy+=olh});oy+=3});
 let items=defs.length?defs:[{motivation:'Sin motivación técnica registrada.',fund:''}],left=.05*c.width,right=.505*c.width,max=.43*c.width,top=.435*c.height,bottom=.522*c.height,reasonFont=16,layout=[];
 for(;reasonFont>=7;reasonFont-=.5){x.font=`${reasonFont}px Arial`;layout=items.map((it,i)=>{let L=wrapText(x,`${i+1}- ${stripSequencePrefix(it.motivation||it.detalle||'')}`,max),R=wrapText(x,`${i+1}- ${stripSequencePrefix(it.fund||'')}`,max);return {L,R,n:Math.max(L.length,R.length)}});let needed=layout.reduce((n,a)=>n+a.n*reasonFont*1.3+4,0);if(needed<=bottom-top)break}
 x.font=`${reasonFont}px Arial`;let y=top,lh=reasonFont*1.3;layout.forEach(({L,R,n})=>{L.forEach((l,j)=>x.fillText(l,left,y+j*lh));R.forEach((l,j)=>x.fillText(l,right,y+j*lh));y+=n*lh+4});return c}
async function canvasJpeg(c){return new Uint8Array(await (await fetch(c.toDataURL('image/jpeg',.94))).arrayBuffer())}
function pdfFromJpeg(jpg,w,h){let objs=[],add=s=>{objs.push(typeof s==='string'?enc.encode(s):s);return objs.length},img=add(concat([enc.encode(`<< /Type /XObject /Subtype /Image /Width ${w} /Height ${h} /ColorSpace /DeviceRGB /BitsPerComponent 8 /Filter /DCTDecode /Length ${jpg.length} >>\nstream\n`),jpg,enc.encode('\nendstream')])),cont=enc.encode(`q\n595 0 0 842 0 0 cm\n/Im0 Do\nQ\n`),content=add(concat([enc.encode(`<< /Length ${cont.length} >>\nstream\n`),cont,enc.encode('endstream')])),page=add(`<< /Type /Page /Parent 4 0 R /MediaBox [0 0 595 842] /Resources << /XObject << /Im0 ${img} 0 R >> >> /Contents ${content} 0 R >>`),pages=add(`<< /Type /Pages /Kids [${page} 0 R] /Count 1 >>`),catalog=add(`<< /Type /Catalog /Pages ${pages} 0 R >>`);let parts=[enc.encode('%PDF-1.7\n%âãÏÓ\n')],offset=[0],pos=parts[0].length;objs.forEach((o,i)=>{offset[i+1]=pos;let p=concat([enc.encode(`${i+1} 0 obj\n`),o,enc.encode('\nendobj\n')]);parts.push(p);pos+=p.length});let xref=pos,s=`xref\n0 ${objs.length+1}\n0000000000 65535 f \n`+offset.slice(1).map(v=>String(v).padStart(10,'0')+' 00000 n \n').join('')+`trailer\n<< /Size ${objs.length+1} /Root ${catalog} 0 R >>\nstartxref\n${xref}\n%%EOF`;parts.push(enc.encode(s));return concat(parts)}
function interactivePdf(jpg,w,h,fields=[]){ // standard page + simple AcroForm text fields
 let base=pdfFromJpeg(jpg,w,h); // rebuild with fields for deterministic AcroForm
 let objs=[],add=s=>{objs.push(typeof s==='string'?enc.encode(s):s);return objs.length},img=add(concat([enc.encode(`<< /Type /XObject /Subtype /Image /Width ${w} /Height ${h} /ColorSpace /DeviceRGB /BitsPerComponent 8 /Filter /DCTDecode /Length ${jpg.length} >>\nstream\n`),jpg,enc.encode('\nendstream')])),cont=enc.encode(`q\n595 0 0 842 0 0 cm\n/Im0 Do\nQ\n`),content=add(concat([enc.encode(`<< /Length ${cont.length} >>\nstream\n`),cont,enc.encode('endstream')]));let fieldIds=[];for(const f of fields){let id=add(`<< /Type /Annot /Subtype /Widget /FT /Tx /T (${String(f.name).replace(/[()]/g,'')}) /Rect [${f.x} ${f.y} ${f.x+f.w} ${f.y+f.h}] /F 4 /V () /DA (/Helv 9 Tf 0 g) >>`);fieldIds.push(id)}let page=add(`<< /Type /Page /Parent ${4+fieldIds.length} 0 R /MediaBox [0 0 595 842] /Resources << /XObject << /Im0 ${img} 0 R >> /Font << /Helv << /Type /Font /Subtype /Type1 /BaseFont /Helvetica >> >> >> /Contents ${content} 0 R /Annots [${fieldIds.map(i=>i+' 0 R').join(' ')}] >>`),pages=add(`<< /Type /Pages /Kids [${page} 0 R] /Count 1 >>`),acro=add(`<< /Fields [${fieldIds.map(i=>i+' 0 R').join(' ')}] /DA (/Helv 9 Tf 0 g) >>`),catalog=add(`<< /Type /Catalog /Pages ${pages} 0 R /AcroForm ${acro} 0 R >>`);let parts=[enc.encode('%PDF-1.7\n%âãÏÓ\n')],offset=[0],pos=parts[0].length;objs.forEach((o,i)=>{offset[i+1]=pos;let p=concat([enc.encode(`${i+1} 0 obj\n`),o,enc.encode('\nendobj\n')]);parts.push(p);pos+=p.length});let xref=pos,s=`xref\n0 ${objs.length+1}\n0000000000 65535 f \n`+offset.slice(1).map(v=>String(v).padStart(10,'0')+' 00000 n \n').join('')+`trailer\n<< /Size ${objs.length+1} /Root ${catalog} 0 R >>\nstartxref\n${xref}\n%%EOF`;parts.push(enc.encode(s));return concat(parts)}
function pdfFields(e){return [{name:'Observaciones adicionales',x:35,y:540,w:525,h:55},{name:'Recibido por',x:45,y:115,w:270,h:18},{name:'Cedula',x:370,y:115,w:170,h:18},{name:'Firma',x:45,y:92,w:270,h:18},{name:'Fecha recibido',x:370,y:92,w:170,h:18}]}
async function downloadOfficePdf(editable=false){let e=expedientes.find(x=>x.id===currentClose);if(!e||e.dictamen==='PENDIENTE'){alert('El expediente aún no tiene resolución final.');return}let c=await officeCanvas(e),jpg=await canvasJpeg(c),pdf=editable?interactivePdf(jpg,c.width,c.height,pdfFields(e)):pdfFromJpeg(jpg,c.width,c.height);blobDownload(pdf,`${safe(e.tramite||caseRef(e))}_${e.dictamen}${editable?'_EDITABLE':''}.pdf`,'application/pdf')}
window.downloadOfficePdf=downloadOfficePdf;

window.CVISADOS_EXPORTADORES={version:VERSION,presentationParts,zipStore,gestionXlsxBytes,officeDocxBytes,officeCanvas,canvasJpeg,pdfFromJpeg,interactivePdf,pdfFields,reportHtml};
renderGestion();refreshReport();
})();
